## p.48 陣列的重塑(reshape())

In [1]:
import numpy as np

In [3]:
grid=np.arange(1,10)
print(grid)
grid_reshape=grid.reshape((3,3))
    #newshape: int or tuple of ints
print(grid_reshape)
np.reshape()

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
#一維轉成column/row of 二維array
x=np.array([9,9,9])
print(x.shape)
    #(3,)
y=np.arange(1,10).reshape((3,3))
print(y,y.shape)

# 把x接在y的column 3，其shape應為(3,1)---np.append()
x.reshape((3,1))
y_append=np.append(y,x.reshape((3,1)),axis=1)
print(y_append)

#把x加入y的column 2---insert
y_append2=np.insert(y,[2],x.reshape((3,1)),axis=1)
    # np.insert(arr, obj, values, axis=None)
    # arr: input array
    # obj : int, slice or sequence of ints
    #       Object that defines the index or indices before which `values` is inserted. 
    # values:  array_like
    # 不同型態的obj會產生不同的結果
print(y_append2)

#把x加入y的row 2
y_append3=np.insert(y,2,x,axis=0)
print(y_append3)

(3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[[1 2 3 9]
 [4 5 6 9]
 [7 8 9 9]]
[[1 2 9 3]
 [4 5 9 6]
 [7 8 9 9]]
[[1 2 3]
 [4 5 6]
 [9 9 9]
 [7 8 9]]


##  陣列的串接和分割-np.concatenate() / np. split()

### 1. 串接

In [31]:
#串接
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])
    # np.concatenate((a1, a2, ...), axis=0, out=None)
    # a1, a2, ... : sequence of array_like
    # axis : int, optional
    #  The axis along which the arrays will be joined.  
    #  If axis is None,arrays are flattened before use.  Default is 0.
    # out : ndarray, optional
    #  If provided, the destination to place the result. The shape must be correct,
    #  matching that of what concatenate would have returned if no out argument were specified.

array([1, 2, 3, 4, 5, 6])

In [32]:
#串接多個array
z=[9,9,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 9, 9, 9])

In [38]:
#二維的串接--相同維度
grid=np.arange(1,10).reshape((3,3))
A=np.concatenate([grid,grid],axis=0)
    # 垂直方向的串接
B=np.concatenate([grid,grid],axis=1)
    # 水平方向的串接
print(A,'\n\n',B)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [10]:
#二維的串接--不同維度  np.vstack/ np.hstack(垂直/水平堆疊)
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])
print(np.vstack([x,grid]))
    #先x後grid
y=np.array([[99],[99]])
print(np.hstack([grid,y]))
    #和append/insert有相同效果

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


### 2. 分割

In [11]:
#np.split
x=[1,2,3,99,57,23,478,15]
x1,x2,x3=np.split(x,[3,5])
    # np.split(ary, indices_or_sections, axis=0)
    # 透過indeces/sections->陣列索引值來指定要分割的點: [3,5]->切成[0:2],[3:4],[5:]
    # n個分割點會產生n+1個子陣列
print(x1,x2,x3)

[1 2 3] [99 57] [ 23 478  15]


In [13]:
#np.hsplit/ np.vsplit
grid=np.arange(16).reshape((4,4))
print(grid)

left,right=np.hsplit(grid,[2])
    #hsplit 是往column方向切
print(left,'\n\n',right

up,low=np.vsplit(grid,[2])
    #vsplit是往row方向切
print(up,'\n\n',low)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]
